// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: logs.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogRequest) Reset() {
	*x = SendLogRequest{}
	mi := &file_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogRequest) ProtoMessage() {}

func (x *SendLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogRequest.ProtoReflect.Descriptor instead.
func (*SendLogRequest) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{0}
}

func (x *SendLogRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SendLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SendLogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendLogRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SendLogRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogResponse) Reset() {
	*x = SendLogResponse{}
	mi := &file_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogResponse) ProtoMessage() {}

func (x *SendLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogResponse.ProtoReflect.Descriptor instead.
func (*SendLogResponse) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{1}
}

func (x *SendLogResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_logs_proto protoreflect.FileDescriptor

const file_logs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"logs.proto\x12\x04logs\"\xfe\x01\n" +
	"\x0eSendLogRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".logs.SendLogRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x0fSendLogResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2D\n" +
	"\n" +
	"LogService\x126\n" +
	"\aSendLog\x12\x14.logs.SendLogRequest\x1a\x15.logs.SendLogResponseB+Z)github.com/my-org/logging-system/pkg/logsb\x06proto3"

var (
	file_logs_proto_rawDescOnce sync.Once
	file_logs_proto_rawDescData []byte
)

func file_logs_proto_rawDescGZIP() []byte {
	file_logs_proto_rawDescOnce.Do(func() {
		file_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)))
	})
	return file_logs_proto_rawDescData
}

var file_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_logs_proto_goTypes = []any{
	(*SendLogRequest)(nil),  // 0: logs.SendLogRequest
	(*SendLogResponse)(nil), // 1: logs.SendLogResponse
	nil,                     // 2: logs.SendLogRequest.MetadataEntry
}
var file_logs_proto_depIdxs = []int32{
	2, // 0: logs.SendLogRequest.metadata:type_name -> logs.SendLogRequest.MetadataEntry
	0, // 1: logs.LogService.SendLog:input_type -> logs.SendLogRequest
	1, // 2: logs.LogService.SendLog:output_type -> logs.SendLogResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_logs_proto_init() }
func file_logs_proto_init() {
	if File_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_proto_goTypes,
		DependencyIndexes: file_logs_proto_depIdxs,
		MessageInfos:      file_logs_proto_msgTypes,
	}.Build()
	File_logs_proto = out.File
	file_logs_proto_goTypes = nil
	file_logs_proto_depIdxs = nil
}
